import type { NationId, TerritoryDef, TerritoryOwner } from './types'

// 131 territories from WR_Territory_List_v1.pdf (authoritative)
// Industry: Y = standard, C = Chinese Mobilization, YC = both

function t(code: string, name: string, startingOwner: TerritoryOwner, sv: number, oil: number, iron: number, osr: number, industry: TerritoryDef['industry'] = null, notes?: string): TerritoryDef {
  return { code, name, startingOwner, sv, oil, iron, osr, industry, isNeutral: startingOwner === null, notes }
}

export const TERRITORIES: TerritoryDef[] = [
  // United States (10)
  t('U1', 'Eastern United States', 'USA', 10, 2, 4, 5, 'Y', 'Capital'),
  t('U2', 'Central United States', 'USA', 9, 3, 4, 6, 'Y'),
  t('U3', 'Western United States', 'USA', 8, 2, 3, 6, 'Y'),
  t('U4', 'Alaska', 'USA', 3, 1, 2, 1),
  t('U5', 'Aleutian Islands', 'USA', 1, 0, 0, 0),
  t('U6', 'Hawaiian Islands', 'USA', 2, 0, 0, 0),
  t('U7', 'Midway Islands', 'USA', 0, 0, 0, 0),
  t('U8', 'Johnston Atoll', 'USA', 0, 0, 0, 0),
  t('U9', 'Samoan Islands', 'USA', 0, 0, 0, 0),
  t('U10', 'New Caledonia', 'USA', 0, 0, 0, 0),
  // British Commonwealth (30)
  t('B1', 'Great Britain', 'UK', 8, 0, 1, 2, 'Y', 'Capital'),
  t('B2', 'Azores', 'UK', 0, 0, 0, 0),
  t('B3', 'Gibralter', 'UK', 1, 0, 0, 0),
  t('B4', 'Malta', 'UK', 1, 0, 0, 0),
  t('B5', 'Egypt', 'UK', 3, 0, 1, 0),
  t('B6', 'Sudan', 'UK', 1, 0, 0, 0),
  t('B7', 'Horn of Africa', 'UK', 1, 0, 0, 0),
  t('B8', 'British East Africa', 'UK', 1, 0, 0, 1),
  t('B9', 'Rhodesia', 'UK', 1, 0, 0, 1),
  t('B10', 'South Africa', 'UK', 3, 0, 1, 1, 'Y'),
  t('B11', 'Belgian Congo', 'UK', 1, 0, 0, 1),
  t('B12', 'French Equatorial Africa', 'UK', 0, 0, 0, 0),
  t('B13', 'Nigeria Cameroon', 'UK', 1, 1, 0, 0),
  t('B14', 'Gold Coast', 'UK', 1, 0, 0, 1),
  t('B15', 'Sierra Leone', 'UK', 1, 0, 0, 0),
  t('B16', 'Middle East', 'UK', 3, 2, 0, 0),
  t('B17', 'Iran', 'UK', 2, 1, 0, 0),
  t('B18', 'India', 'UK', 5, 0, 0, 2, 'Y'),
  t('B19', 'Ceylon', 'UK', 0, 0, 0, 0),
  t('B20', 'Maldives', 'UK', 0, 0, 0, 0),
  t('B21', 'Western Australia', 'UK', 1, 0, 0, 1),
  t('B22', 'Northern Territory', 'UK', 1, 0, 0, 1),
  t('B23', 'South Australia', 'UK', 2, 0, 1, 0),
  t('B24', 'Eastern Australia', 'UK', 3, 0, 1, 1, 'Y'),
  t('B25', 'Papua', 'UK', 1, 0, 0, 0),
  t('B26', 'New Hebrides', 'UK', 0, 0, 0, 0),
  t('B27', 'New Zealand', 'UK', 2, 0, 0, 0),
  t('B28', 'Western Canada', 'UK', 3, 1, 2, 1),
  t('B29', 'Eastern Canada', 'UK', 4, 0, 1, 1, 'Y'),
  t('B30', 'The Guyanas', 'UK', 0, 0, 0, 0),
  // Soviet Union (18)
  t('R1', 'Moscow', 'USSR', 5, 0, 1, 1, 'Y', 'Capital'),
  t('R2', 'Arkhangelsk', 'USSR', 3, 0, 0, 1, 'Y'),
  t('R3', 'Karelia', 'USSR', 2, 1, 0, 0, 'Y'),
  t('R4', 'Leningrad', 'USSR', 3, 0, 0, 1, 'Y'),
  t('R5', 'Bryansk', 'USSR', 2, 0, 1, 1, 'Y'),
  t('R6', 'Caucasus', 'USSR', 3, 2, 0, 0),
  t('R7', 'Volga', 'USSR', 2, 0, 1, 1, 'Y'),
  t('R8', 'Kazakh', 'USSR', 1, 0, 0, 2),
  t('R9', 'Turkmen Uzbek', 'USSR', 1, 0, 0, 0),
  t('R10', 'East Kazakh', 'USSR', 1, 0, 0, 0),
  t('R11', 'Sverdlovsk', 'USSR', 3, 0, 0, 2),
  t('R12', 'Urals', 'USSR', 2, 2, 0, 0),
  t('R13', 'Krasnoyarsk', 'USSR', 1, 1, 0, 0),
  t('R14', 'Amur Irkutsk', 'USSR', 2, 0, 1, 1),
  t('R15', 'Yakut', 'USSR', 2, 1, 0, 0),
  t('R16', 'Khabarovsky', 'USSR', 2, 0, 1, 0, 'Y'),
  t('R17', 'Kamchatsky', 'USSR', 1, 0, 1, 0),
  t('R18', 'Soviet Sakhalin Island', 'USSR', 0, 0, 0, 0),
  // Germany (16)
  t('G1', 'Greater Germany', 'GER', 8, 1, 2, 3, 'Y', 'Capital'),
  t('G2', 'Denmark', 'GER', 1, 0, 0, 1),
  t('G3', 'France', 'GER', 6, 0, 2, 3, 'Y'),
  t('G4', 'Poland Slovakia Hungary', 'GER', 4, 0, 2, 3, 'Y'),
  t('G5', 'Bulgaria Rumania', 'GER', 4, 2, 0, 2, 'Y'),
  t('G6', 'Ukraine', 'GER', 4, 1, 0, 3, 'Y'),
  t('G7', 'Belarus', 'GER', 2, 0, 2, 1, 'Y'),
  t('G8', 'Baltic States', 'GER', 1, 0, 0, 1),
  t('G9', 'Finland', 'GER', 2, 0, 2, 0),
  t('G10', 'Norway', 'GER', 2, 0, 1, 0),
  t('G11', 'French Morocco', 'GER', 2, 1, 0, 1),
  t('G12', 'Algeria', 'GER', 2, 1, 0, 0),
  t('G13', 'Tunisia', 'GER', 1, 0, 1, 0),
  t('G14', 'Crete', 'GER', 1, 0, 0, 0),
  t('G15', 'French West Africa', 'GER', 1, 0, 0, 1),
  t('G16', 'Madagascar', 'GER', 0, 0, 0, 0),
  // Imperial Japan (28)
  t('J1', 'Imperial Japan', 'JAP', 8, 0, 2, 2, 'Y', 'Capital'),
  t('J2', 'Korea', 'JAP', 2, 0, 1, 1),
  t('J3', 'Manchuria', 'JAP', 3, 0, 3, 1, 'C', 'Chinese Mobilization'),
  t('J4', 'Peiping', 'JAP', 2, 0, 1, 2, 'YC', 'Industry + Chinese Mobilization'),
  t('J5', 'Chekiang Kwangtung', 'JAP', 2, 0, 2, 1, 'C', 'Chinese Mobilization'),
  t('J6', 'Indochina', 'JAP', 1, 0, 0, 1),
  t('J7', 'Thailand', 'JAP', 1, 0, 0, 2),
  t('J8', 'Burma', 'JAP', 1, 0, 0, 1),
  t('J9', 'Malaya', 'JAP', 2, 0, 0, 2),
  t('J10', 'Sumatra', 'JAP', 2, 3, 0, 0),
  t('J11', 'Java', 'JAP', 2, 2, 0, 0),
  t('J12', 'Borneo', 'JAP', 2, 2, 0, 1),
  t('J13', 'Celebes', 'JAP', 0, 0, 0, 0),
  t('J14', 'Philippines', 'JAP', 2, 0, 1, 2),
  t('J15', 'Hainan', 'JAP', 0, 0, 0, 0),
  t('J16', 'Formosa', 'JAP', 1, 0, 0, 0),
  t('J17', 'Okinawa', 'JAP', 1, 0, 0, 0),
  t('J18', 'Palau', 'JAP', 0, 0, 0, 0),
  t('J19', 'Japanese Sakhalin Island', 'JAP', 0, 0, 0, 0),
  t('J20', 'Iwo Jima', 'JAP', 1, 0, 0, 0),
  t('J21', 'Mariana Islands', 'JAP', 0, 0, 0, 0),
  t('J22', 'Caroline Islands', 'JAP', 2, 0, 0, 0),
  t('J23', 'New Britain', 'JAP', 1, 0, 0, 0),
  t('J24', 'New Guinea', 'JAP', 1, 0, 0, 0),
  t('J25', 'Solomon Islands', 'JAP', 1, 0, 0, 0, null, 'Embattled at start'),
  t('J26', 'Wake Island', 'JAP', 0, 0, 0, 0),
  t('J27', 'Marshall Islands', 'JAP', 0, 0, 0, 0),
  t('J28', 'Gilbert Islands', 'JAP', 0, 0, 0, 0),
  // Italy (5)
  t('T1', 'Italy', 'ITA', 6, 0, 1, 3, 'Y', 'Capital'),
  t('T2', 'Balkans', 'ITA', 4, 1, 2, 3),
  t('T3', 'Sardinia', 'ITA', 1, 0, 0, 0),
  t('T4', 'Sicily', 'ITA', 1, 0, 0, 0),
  t('T5', 'Libya', 'ITA', 3, 2, 1, 0),
  // China (5)
  t('C1', 'Honan', 'CHN', 1, 0, 0, 1, 'C'),
  t('C2', 'Kwangsi', 'CHN', 1, 0, 0, 1, 'C'),
  t('C3', 'Szechwan Yunnan', 'CHN', 1, 0, 0, 2, 'C'),
  t('C4', 'Tsinghai Ningsia', 'CHN', 2, 0, 1, 2, 'C'),
  t('C5', 'Sinkiang', 'CHN', 1, 0, 1, 0, 'C'),
  // Neutrals (19)
  t('N1', 'Mexico', null, 0, 0, 0, 0, null, 'Pro-Allied, trades Iron'),
  t('N2', 'Central America', null, 0, 0, 0, 0, null, 'Pro-Allied'),
  t('N3', 'West Indies', null, 0, 0, 0, 0, null, 'Pro-Allied'),
  t('N4', 'Colombia', null, 0, 0, 0, 0, null, 'Trades OSR'),
  t('N5', 'Venezuela', null, 0, 0, 0, 0, null, 'Trades Oil'),
  t('N6', 'Brazil', null, 0, 0, 0, 0, null, 'Pro-Allied, trades Iron'),
  t('N7', 'Greenland', null, 0, 0, 0, 0, null, 'Pro-Allied'),
  t('N8', 'Iceland', null, 0, 0, 0, 0, null, 'Pro-Allied'),
  t('N9', 'Ireland', null, 0, 0, 0, 0),
  t('N10', 'Sweden', null, 0, 0, 0, 0, null, 'Trades Iron'),
  t('N11', 'Spain', null, 0, 0, 0, 0, null, 'Trades OSR'),
  t('N12', 'Portugal', null, 0, 0, 0, 0),
  t('N13', 'Switzerland', null, 0, 0, 0, 0),
  t('N14', 'Turkey', null, 0, 0, 0, 0),
  t('N15', 'Arabia', null, 0, 0, 0, 0, null, 'Trades Oil'),
  t('N16', 'Angola', null, 0, 0, 0, 0),
  t('N17', 'Mozambique', null, 0, 0, 0, 0),
  t('N18', 'Afghanistan', null, 0, 0, 0, 0),
  t('N19', 'Mongolia', null, 0, 0, 0, 0),
]

/** Lookup by code */
export const TERRITORY_MAP: Record<string, TerritoryDef> = Object.fromEntries(
  TERRITORIES.map(t => [t.code, t])
)

/** Starting territories per nation */
export const STARTING_TERRITORIES: Record<NationId, string[]> = {
  USA: TERRITORIES.filter(t => t.startingOwner === 'USA').map(t => t.code),
  UK: TERRITORIES.filter(t => t.startingOwner === 'UK').map(t => t.code),
  USSR: TERRITORIES.filter(t => t.startingOwner === 'USSR').map(t => t.code),
  CHN: TERRITORIES.filter(t => t.startingOwner === 'CHN').map(t => t.code),
  GER: TERRITORIES.filter(t => t.startingOwner === 'GER').map(t => t.code),
  ITA: TERRITORIES.filter(t => t.startingOwner === 'ITA').map(t => t.code),
  JAP: TERRITORIES.filter(t => t.startingOwner === 'JAP').map(t => t.code),
}
